# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c0339e265fb9692d36d0b73abe0ad7ecdce2316f7f580cf665f842121c4767c2837827bcb1a6cb46254ba0377bedf295147be6928eaafc7da0e151679f2158

test:
  secret_key_base: 1feb9ac68beb3b6fd780c0c0aacf5231594f0ff013de919b8632887198e7fa040e78cfa95f36d2aaf33e41d7dbe3d50c82257db73bd8a31fc82637ae26153dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
